attempt_thresholds:
  download: 3
  wayback: 3
  archive: 3
  hf: 3
hf:
  dataset_repo_url: https://huggingface.co/datasets/Orgpedia/mahGRs
  dataset_repo_id: Orgpedia/mahGRs
  dataset_repo_path: import/downloads
  upload_large_folder_mode: auto
  upload_large_folder_threshold: 100
